---
title: "LowN_10_18_21"
author: "Dylan Baker"
date: "11/2/2021"
output: html_document
---
    ```{r setup, include=FALSE}
    knitr::opts_chunk$set(eval = TRUE, 
                          echo = TRUE, 
                          cache = TRUE,
                          include = TRUE,
                          collapse = FALSE,
                          dependson = NULL,
                          warning = FALSE,
                          engine = "R", # Chunks will always have R code, unless noted
                          error = TRUE)

    library(tidyverse)
    library(patchwork)
    library(lubridate)
    library(ggpubr)
    library(broom)
    library(grid)

source("functions.R")
    ```

```{r Data import, warning=FALSE}
#Make a list of the paths of files so that R can import with read_csv
file_list <- list.files(path = "./data/low_N_10_18_21",
                        full.names = TRUE, ignore.case = TRUE, pattern = "^Plate.*.csv")

#Import plate data with annotations
data_all <-
  file_list %>%
  map_df(~read_data(.)) |>
  group_by(`Well ID`,Plate) |>
  dplyr::mutate(begin = min(read_time),
         read_interval = begin %--% read_time,
         read_timeDays = as.numeric(as.duration((read_interval)/ddays(1)))) |>
  ungroup()

#Plate reader did not include some blank time data, so need to pull time data from existing blanks
blank_data <- data_all |>
  filter(`Well ID` == "BLK") |>
  dplyr::select(read_day,Plate,read_time, read_timeDays)
empty_blank <- data_all |>
  filter(is.na(`Well ID`)) |>
  dplyr::select(-c(`Well ID`, read_timeDays, read_time))
filled_blank <- left_join(empty_blank, blank_data,
                           by = c("Plate","read_day"))
#Merge data back together, then filter out empty blank data
data_all <- bind_rows(data_all, filled_blank) |>
  filter(!is.na(read_timeDays)) |>
  unique() |>
  #Reads start at day 1, when it should actually be day 0.
  dplyr::mutate(read_day = read_day - 1)

#Import plate map data
map_data <- read_csv("./data/lowN_10_18_21_map.csv")

#Some media control data lost in this step due to plate reader error. Not missing any sample data.
full_data <- inner_join(data_all, map_data,
                        by = c("Well", "Plate")) |>
  group_by(Plate,Well,Culture, State, N_ug_L) |>
  arrange(read_timeDays) |>
  dplyr::mutate(#evaporation constant derived from random wells sampled at experiment end. See plate_evap_data for rationale
         evap_correction = (1 - read_timeDays * 0.002761443318),
         PC_100_true = PC_100 * evap_correction + 1 ,
         chlA_150_true = chlA_150 * evap_correction + 1,
         ln_PC_diff = log(PC_100_true/lag(PC_100_true)),
         ln_chlA_diff = log(chlA_150_true/lag(chlA_150_true)),
         time_diff = read_timeDays - lag(read_timeDays),
         growthrate_PC = ln_PC_diff/time_diff,
         growthrate_chlA = ln_chlA_diff/time_diff) |>
  dplyr::select(Well, Plate, Treatment_name,Culture, State, N_ug_L,chlA_150, chlA_150_true, PC_100,PC_100_true,read_day,read_time,read_timeDays, growthrate_PC, growthrate_chlA) |>
  unite(Plate, Well, sep = "_", col = p_well, remove = FALSE) |>
  ungroup()


write.csv(full_data, file = "./data/lowN_data_full_101821.csv")
```

```{r plotting growth curves}
facet_data <- full_data |>
  dplyr::mutate(N_level = factor(paste(N_ug_L, "μg/L N")))

blank_facets <- subset(facet_data, Culture == "Media_CTRL") |>
  group_by(Plate, read_day, read_timeDays) |>
  dplyr::mutate(PC_100_true = mean(PC_100_true)) |>
  filter(!duplicated(PC_100_true))

sample_facets <- subset(facet_data, Culture != "Media_CTRL") |>
  dplyr::mutate(facet1 = N_level, 
         facet2 = State) 

all_facets <- merge(blank_facets, data.frame(unique(sample_facets[c("facet1","facet2")])))

plot_data <- rbind(all_facets, sample_facets)|>
  filter(facet1 != "883 μg/L N")

PC_plot_N <- ggplot(data = plot_data, aes(x = read_timeDays, y = log10(PC_100_true), color = Culture)) +
   geom_point(size = 1.5, shape = 21) +
   scale_color_manual(values = c("NIES_843" = "cyan3",
                                 "PCC_9701" = "darkgoldenrod2",
                                "WT_7806" =  "firebrick3",
                                "MUT_7806" = "chartreuse2",
                                "Media_CTRL" = "gray"),
                      labels = c("NIES_843" = "NIES-843", 
                                 "PCC_9701" = "PCC 9701",
                                 "WT_7806" = "PCC 7806",
                                 "MUT_7806" = "PCC 7806 ΔmcyB", 
                                "Media_CTRL" = "Media Control")
                      ) +
   geom_line(aes(group = p_well)) +
   ylab("Log 10, Phycocyanin Fluorescence") +
   xlab("Time (days)") +
   xlim(0, 19) +
   coord_cartesian(ylim = c(0,3.5), expand = F) +
   facet_wrap(~factor(facet1, 
                       levels = c("8 μg/L N","40.5 μg/L N",
                                  "87 μg/L N"
                                   ,"425 μg/L N",
                                    "2760 μg/L N"
                                   ,"14150 μg/L N", "30500 μg/L N"
                                  )) + facet2, nrow = 4) +
  theme_pubr(border = T, base_size = 14) +
  theme(strip.text = element_text(size = 12),
        legend.direction = "vertical") 


png(filename = "./figures/Finalized Figs for Publication/figure2_final.png",
    res = 600,
    type = "cairo",
    units = "mm",
    width = 180,
    height = 250)

grid.draw(shift_legend(PC_plot_N))

dev.off()

# chlA_plot_N <- ggplot(data = plot_data, aes(x = read_timeDays, y = chlA_150_true, color = Culture)) +
#    geom_point(size = 2, shape = 21) +
#    scale_color_manual(values = c("NIES_843" = "cyan3",
#                                  "PCC_9701" = "darkgoldenrod2",
#                                 "WT_7806" =  "firebrick3",
#                                 "MUT_7806" = "chartreuse2",
#                                 "Media_CTRL" = "black")) +
#    geom_line(aes(group = p_well)) +
#    ylab("Log 10, Cells per mL") +
#    xlab("Time (days)") +
#    xlim(0, 17) +
#    ylim(0, 100) +
#    facet_wrap(Culture ~fct_relevel(facet1, 
#                        levels = c("8 μg/L N","40 μg/L N",
#                                   "87 μg/L N"
#                                   # ,"425 μg/L N",
#                                   # "883 μg/L N", "2760 μg/L N",
#                                   # "14150 μg/L N", "30500 μg/L N"
#                                   )) + facet2) +
#   theme_pubclean() +
#   theme(strip.text = element_text( size = 12),
#         legend.position = "bottom"
#         )
# png(filename = "./figures101821_growthcurves_chlA150.png",
#     res = 300,
#     type = "cairo",
#     units = "in",
#     width = 10,
#     height = 10)
# chlA_plot_N
# dev.off()


```
Run a linear regression on all samples to determine slopes. Run a t-test against blank samples to determine if a growthrate can be calculated. If the sample triplicates are not significantly greater from the blanks, then those will be excluded and growthrate will be listed as 0.
```{r Linear regression to discern growth from blank}
MC <- full_data |>
  filter(Culture == "Media_CTRL")

c(lowN_101821_ttests,sample_lm) := full_data |>
  filter(read_timeDays < 18, Culture != "Media_CTRL") |>
  group_by(p_well) |>
  dplyr::mutate(peak_time = ifelse(PC_100_true == max(PC_100_true), read_timeDays, -1)) |> #mark when the highest fluorescence value is reached, filter below that timepoint
  filter(read_timeDays <= max(peak_time)) |>
  ungroup() |>
  filter(!peak_time == 0) |>
  full_join(MC) |>
  slope_ttests( pigment = "PC_100_true", N_or_P = "N")

sample_lm <- bind_rows(sample_lm)

c(lowN_101821_ttests_chlA, sample_lm_chlA) := full_data |>
  filter(read_timeDays < 15) |>
  slope_ttests(pigment = "chlA_150_true", N_or_P = "N")
sample_lm_chlA <- bind_rows(sample_lm_chlA)

gr_PC <- full_data |>
  filter(Culture != "Media_CTRL", 
         !is.na(growthrate_chlA), !is.na(growthrate_PC),
         growthrate_PC > 0) |>
  group_by(Culture, State, N_ug_L, Plate, Well, Treatment_name) |>
  slice_max(n = 5, growthrate_PC) |>
  dplyr::summarise(gr_chlA_mean = mean(growthrate_chlA),
            gr_PC_mean = mean(growthrate_PC),
            gr_chlA_sd = sd(growthrate_chlA),
            gr_pc_sd = sd(growthrate_PC),
            n_obs = n(),
            gr_chlA_se = gr_chlA_sd / sqrt(n_obs),
            gr_pc_se = gr_pc_sd / sqrt(n_obs),
            chlA_upper_cl = gr_chlA_mean + gr_chlA_se,
            chlA_lower_cl = gr_chlA_mean - gr_chlA_se,
            pc_upper_cl = gr_PC_mean + gr_pc_se,
            pc_lower_cl = gr_PC_mean - gr_pc_se) |>
  left_join(lowN_101821_ttests, by = "Treatment_name", copy = TRUE) |>
  dplyr::mutate(growthrate_corrected = case_when(N_ug_L == 40.5 ~ 0,
                                          p.value < (0.05) ~ gr_PC_mean,
                                          is.na(p.value) ~ 0,
                                          T ~ 0),
         gr_pc_se_corrected = ifelse(growthrate_corrected == 0, 0, gr_pc_se)) |>
  dplyr::select(Culture, State, N_ug_L, gr_PC_mean, gr_pc_se_corrected, p.value, growthrate_corrected)

write.csv(gr_PC, file = "./data/growthrate_estimates_N.csv")

gr_PC_plot <- ggplot(data = filter(gr_PC, !N_ug_L == 883), aes(x = N_ug_L, y = growthrate_corrected)) +
   geom_point(color = "skyblue",
              size = 2) +
   ylab("μ (1/day)") +
   xlab("Nitrogen (μg/L)") +
   coord_cartesian(ylim = c(0.0,1.0)) +
   facet_grid(factor(Culture, 
                     levels = c("MUT_7806", "WT_7806", "PCC_9701", "NIES_843"), 
                     labels = c("PCC 7806 ΔmcyB", "PCC 7806", "PCC 9701", "NIES-843")  )  ~ State) +
   stat_smooth(color = "black", 
               size = 0.7,
               method = "nls",
               se = FALSE,
               method.args = list(
                 formula = y~mumax*x/(x + ks),
                 start = list(mumax = 0.5, ks = 30)
               )) +
  geom_errorbar(mapping = aes(ymin = growthrate_corrected - gr_pc_se_corrected,
                              ymax = growthrate_corrected + gr_pc_se_corrected), width = 400) +
  theme_pubr(border = T, base_size = 14) +
  theme(strip.text = element_text(size = 12),
        axis.text.x = element_text(angle = 60, hjust = 1)
        )


png(file = "./figures/figure_pieces/Figure4B.png",
    type = "cairo",
    units = "mm",
    res = 600, width = 180, height = 180)

gr_PC_plot

dev.off()

#Saved for later to incorporate with fig2A to make final figure 2
saveRDS(gr_PC_plot, file = "./figures/figure_pieces/fig4B.rds")

gr_chlA <- full_data |>
  filter(Culture != "Media_CTRL", 
         #read_timeDays > 5, read_timeDays < 14,
         !is.na(growthrate_chlA), !is.na(growthrate_PC),
         growthrate_chlA > 0) |>
  group_by(Culture, State, N_ug_L, Plate, Well, Treatment_name) |>
  slice_max(n = 5, growthrate_PC) |>
  dplyr::summarise(gr_chlA_mean = mean(growthrate_chlA),
            gr_PC_mean = mean(growthrate_PC),
            gr_chlA_sd = sd(growthrate_chlA),
            gr_pc_sd = sd(growthrate_PC),
            n_obs = n(),
            gr_chlA_se = gr_chlA_sd / sqrt(n_obs),
            gr_pc_se = gr_pc_sd / sqrt(n_obs)) |>
  left_join(lowN_101821_ttests, by = "Treatment_name", copy = TRUE) |>
  dplyr::mutate(growthrate_corrected = ifelse(p.value < (0.05), gr_chlA_mean, 0),
         gr_chlA_se_corrected = ifelse(growthrate_corrected == 0, 0, gr_chlA_se)) |>
  filter((!growthrate_corrected == 0 | N_ug_L < 100)) |>
  dplyr::select(Culture, State, N_ug_L, gr_chlA_mean, gr_chlA_se_corrected, p.value, growthrate_corrected)

gr_chlA_plot <- ggplot(data = gr_chlA, aes(x = N_ug_L, y = growthrate_corrected)) +
   geom_point(color = "#09f073",
              size = 2) +
   ylab("μ (1/day)") +
   xlab("Nitrogen (μg/L)") +
   facet_grid(factor(Culture, 
                     levels = c("MUT_7806", "WT_7806", "PCC_9701", "NIES_843"), 
                     labels = c("PCC 7806 ΔmcyB", "PCC 7806", "PCC 9701", "NIES-843")  )  ~ State) +
   geom_smooth(color = "black", 
               size = 0.7,
               method = "nls",
               se = FALSE,
               formula = y~mumax*x/(x + ks),
               method.args = list(
                 start = list(mumax = 0.5, ks = 30),
                 control = nls.control(maxiter = 200)
               )) +
  geom_errorbar(mapping = aes(ymin = growthrate_corrected - gr_chlA_se_corrected,
                              ymax = growthrate_corrected + gr_chlA_se_corrected), width = 250) +
  #labs(title = "Chlorophyll-A Manual") +
   ylim(0,1) +
  theme_pubr(border = T, base_size = 14) +
  theme(strip.text = element_text( size = 12),
        axis.text.x = element_text(angle = 60, hjust = 0.4, vjust = 0.5)
        ) 
fig_S1 <- ggarrange(common.legend = T, nrow = 1, labels = "AUTO", gr_PC_plot, gr_chlA_plot)

ggsave('./figures/Finalized Figs for Publication/FigureS1_final.png',fig_S1,width = 180, height = 200, units = "mm", dpi = 600)

```

